### ISSUE TITLE
l9标题有特殊符号会报错

### ISSUE THREAD

**Issue by theurgist0** [IshtarTang/lofterSpider#15]
标题有emoji：
```
准备保存：?? ，原文连接： https://rp1945602.lofter.com/post/1cdf7241_1cab02ac0     Traceback (most recent call last):
  File "/Users/yb/lofterSpider/l9_author_txt.py", line 481, in <module>
    run(author_url, login_key, login_auth, get_comm, additional_break, start_time, end_time, chapter_merge_title,
  File "/Users/yb/lofterSpider/l9_author_txt.py", line 307, in run
    all_file_name = save_file(blog_infos, author_name, author_ip, get_comm, additional_break)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yb/lofterSpider/l9_author_txt.py", line 138, in save_file
    article_content = parse_template.get_content(parse, template_id, title, blog_type, join_word)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yb/lofterSpider/parse_template.py", line 134, in get_content
    content = all_purpose_template(parse, title, blog_type, join_word)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yb/lofterSpider/parse_template.py", line 37, in all_purpose_template
    content = content.split(title, 2)[2]
              ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: empty separator
```

其他特殊符号
```
准备保存：列车驶向__  Der Zug f?hrt auf__ ，原文连接： https://rp1945602.lofter.com/post/1cdf7241_1c6b088e5     Traceback (most recent call last):
  File "/Users/yb/lofterSpider/l9_author_txt.py", line 481, in <module>
    run(author_url, login_key, login_auth, get_comm, additional_break, start_time, end_time, chapter_merge_title,
  File "/Users/yb/lofterSpider/l9_author_txt.py", line 307, in run
    all_file_name = save_file(blog_infos, author_name, author_ip, get_comm, additional_break)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yb/lofterSpider/l9_author_txt.py", line 138, in save_file
    article_content = parse_template.get_content(parse, template_id, title, blog_type, join_word)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yb/lofterSpider/parse_template.py", line 134, in get_content
    content = all_purpose_template(parse, title, blog_type, join_word)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yb/lofterSpider/parse_template.py", line 37, in all_purpose_template
    content = content.split(title, 2)[2]
              ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by theurgist0** [comment]
另外登录验证用NTES_SESS是没问题的

**Comment by IshtarTang** [comment]
感谢反馈，已修复
