### ISSUE TITLE
l9_author_txt 好像用不了了

### ISSUE THREAD

**Issue by scybbq** [IshtarTang/lofterSpider#8]
链接 https://weitayiji.lofter.com/
报错 
Traceback (most recent call last):
  File "E:\py\lofterSpider-master\l9_author_txt.py", line 472, in <module>
    run(author_url, get_comm, additional_break, start_time, end_time, chapter_merge_title, additional_chapter_index)
  File "E:\py\lofterSpider-master\l9_author_txt.py", line 273, in run
    author_id = author_page_parse.xpath("//body/iframe[@id='control_frame']/@src")[0].split("blogId=")[1]
IndexError: list index out of range

**Comment by IshtarTang** [comment]
之前访问博客主页不用登录，我的代码就没做登录步骤，最近改版成要登录的了，我修一下去

**Comment by IshtarTang** [comment]
修好了
