### ISSUE TITLE
l9、l10都有这个报错，不知道是什么情况？

### ISSUE THREAD

**Issue by Ltmte** [IshtarTang/lofterSpider#9]
Traceback (most recent call last):
  File "D:\PythonFiles\lofterSpider-master\l10_blogs_txt.py", line 111, in <module>
    archives_info = save_files(blog_urls)
  File "D:\PythonFiles\lofterSpider-master\l10_blogs_txt.py", line 77, in save_files
    time_and_title = get_time_and_title(blog_url, author_page_parse)
  File "D:\PythonFiles\lofterSpider-master\l10_blogs_txt.py", line 24, in get_time_and_title
    author_id = author_page_parse.xpath("//body/iframe[@id='control_frame']/@src")[0].split("blogId=")[1]
IndexError: list index out of range

**Comment by IshtarTang** [comment]
之前访问博客主页不用登录，我的代码就没做登录步骤，最近改版成要登录的了，我修一下去

**Comment by IshtarTang** [comment]
修好了

**Comment by Ltmte** [comment]
> 修好了

感谢！
